---
- hosts: webservers
  tasks:
  - name: Add Docker GPG apt Key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts["lsb"]["codename"]}} stable
      state: present

  - name: Update apt and install dependencies
    become: true
    apt:
      pkg:
        - docker-ce
        - docker-compose
        - git
      state: latest
      update_cache: true

  - name: Added the ansible user to docker group
    become: true
    ansible.builtin.user:
      append: true
      name: "{{ ansible_user_id }}"
      groups: docker

  - name: Reset ssh connection to allow user changes to affect ansible user
    ansible.builtin.meta:
      reset_connection

  - name: Git checkout app
    ansible.builtin.git:
      repo: 'https://github.com/sourceallies/python-deploy-technically-speaking.git'
      dest: ~/app
      force: true

  - openssl_privatekey:
      path: ~/app/deploy/ssl/domain.key
      size: 2048

  - openssl_csr:
      path: ~/app/deploy/ssl/domain.csr
      privatekey_path: ~/app/deploy/ssl/domain.key

  - openssl_certificate:
      provider: selfsigned
      path: ~/app/deploy/ssl/domain.crt
      privatekey_path: ~/app/deploy/ssl/domain.key
      csr_path: ~/app/deploy/ssl/domain.csr

  - name: Create and start service
    community.docker.docker_compose:
      project_src: ~/app/deploy
